# Namespace
namespace: app

# Application
app:
  name: time-series
  replicas: 1
  terminationGracePeriodSeconds: 10
  serviceAccountName: filebeat
  image:
    repository: neeabhishek/time_series
    tag: v2
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "500Mi"
  volumeMounts:
  - name: time-series-logs
    mountPath: /app/logs/

  service:
    name: time-series-service
    type: NodePort
    port: 80
    nodePort: 30000
    targetPort: 5000
  logPaths:
  - /app/logs/application.log
  - /app/logs/access.log

# Filebeat
filebeat:
  name: filebeat
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 8.15.0
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  volumeMounts:
  - name: time-series-logs
    mountPath: /app/logs/
  - name: filebeat-config
    mountPath: /usr/share/filebeat/filebeat.yml
    subPath: filebeat.yml
  volumes:
  - name: time-series-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:
      name: filebeat-config
  output:
    logstashHost: logstash
    logstashPort: 5044

# Logstash
logstash:
  name: logstash
  replicas: 1
  image:
    repository: docker.elastic.co/logstash/logstash
    tag: 8.15.0
  volumeMounts:
  - name: logstash-pipeline
    mountPath: /usr/share/logstash/pipeline
  volumes:
  - name: logstash-pipeline
    configMap:
      name: logstash-pipeline
  service:
    type: ClusterIP
    port: 5044
  pipeline:
    indexPrefix: time-series-app-logs

# Elasticsearch
elasticsearch:
  name: elasticsearch
  replicas: 1
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.15.0
  volumeMounts:
  - name: config
    mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
    subPath: elasticsearch.yml
  volumes:
  - name: config
    configMap:
      name: elastic-search-config
  service:
    type: ClusterIP
    port: 9200

# Kibana
kibana:
  name: kibana
  replicas: 1
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 8.15.0
  service:
    nodePort: 30001
    port: 5601
    type: NodePort
