apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.service.name }}
    namespace: {{ .Values.namespace }}
spec:
    type: {{ .Values.app.service.type }}
    selector:
        app: {{ .Values.app.name }}
    ports:
        - targetPort: {{ .Values.app.service.targetPort }}
          port: {{ .Values.app.service.port }}
          nodePort: {{ .Values.app.service.nodePort }}