apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      serviceAccountName: {{ .Values.app.serviceAccountName }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          ports:
            - containerPort: 5000

        - name: file-beat
          image: "{{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          args:
            - "-c"
            - "/usr/share/filebeat/filebeat.yml"
            - "-e"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.filebeat.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.filebeat.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.filebeat.volumes | nindent 8 }}
