apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.elasticsearch.service.type  }}
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}