apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-search-config
  namespace: {{ .Values.namespace }}
data:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.enrollment.enabled: false