apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.filebeat.name }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
    verbs: ["get","list","watch"]


