apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: {{ .Values.kibana.name }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
      nodePort: {{ .Values.kibana.service.nodePort }} 
