apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.logstash.name }}
    namespace: {{ .Values.namespace}}
spec:
    type: {{ .Values.logstash.service.type }}
    selector:
        app: {{ .Values.logstash.name }}
    ports:
        - targetPort: {{ .Values.logstash.service.port }}
          port: {{ .Values.logstash.service.port }}